FactoryWebApplication/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FactoryWebApplication.Models
{
    public class Employee
    {
       public string firstName;
      public  string lastName;
      public  int yearOfBirth;
      public  string phone;

        public string FirstName { get { return firstName; } set { firstName = value; } }
        public string LastName { get { return lastName; } set { lastName = value; } }
        public int YearOfBirth { get { return yearOfBirth; } set { yearOfBirth = value; } }
        public string Phone { get { return phone; } set { phone = value; } }


       public Employee() { }

        public Employee(string firstName, string lastName, int yearOfBirth, string phone)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.yearOfBirth = yearOfBirth;
            this.phone = phone;
        }
        
         
        
    }
}

FactoryWebApplication/Models/Inspector.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FactoryWebApplication.Models
{
    public class Inspector
    {
       public string firstName;
       public string lastName;
       public int yearOfBirth;
       public int workExperience;


        public string FirstName { get { return firstName; } set { firstName = value; } }
        public string LastName { get { return lastName; } set { lastName = value; } }
        public int YearOfBirth { get { return yearOfBirth; } set { yearOfBirth = value; } }
        
        public int WorkExperience { get { return workExperience; } set { workExperience = value; } }


       public Inspector(string firstName,string lastName,int yearOfBirth,int workExperience)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.yearOfBirth = yearOfBirth;
            this.workExperience = workExperience;

        }


    }
}

FactoryWebApplication/Models/Manager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FactoryWebApplication.Models
{
    public class Manager
    {
       public string firstName;
       public string lastName;
       public string department;

        public string FirstName { get { return firstName; } set { firstName = value; } }
        public string LastName { get { return lastName; } set { lastName = value; } }

        public string Department { get { return department; } set { department = value; } }
      public  Manager(string firstName, string lastName, string department)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.department = department;
        }
    }
}

FactoryWebApplication/Controllers/EmployeeController.cs
using FactoryWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FactoryWebApplication.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowEmployeeName()
        {

            string employeeName = "bob";

            ViewBag.EmployeeName = employeeName;

            return View();
        }


        public ActionResult ShowEmployee()
        {
            return View();
        }

        public ActionResult ShowEmployeesNames()
        {
            string[] employeesNames = new string[] { "matan", "lior", "haim", "marcos", "ben","yosi" };

            ViewBag.EmployeeNames = employeesNames;

            return View();
        }


        public ActionResult ShowEmployees()
        {
            return View();
        }

        public ActionResult EmployeeOjb()
        {

            Employee employee = new Employee("matan","ysayas",1996,"08542154");

           

            return View(employee);

        }


        public ActionResult EmployeeList()
        {
            List <Employee>  employeesList = new List<Employee>(6);
            employeesList.Add(new Employee("rob", "avi", 1996, "8558787"));
            employeesList.Add(new Employee("haim", "yosi", 1995, "55656"));
            employeesList.Add(new Employee("sdsd,", "sdsds", 2000, "8975454"));
            employeesList.Add(new Employee("eeee", "sdsd", 1998, "777777"));
            employeesList.Add(new Employee("eewewe,", "swewe", 2013, "8975454"));
            employeesList.Add(new Employee("eeee", "sdsd", 1969, "96968857"));


            return View(employeesList);
        }


    }
}

FactoryWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FactoryWebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FactoryWebApplication/Controllers/InspectorController.cs
using FactoryWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FactoryWebApplication.Controllers
{
    public class InspectorController : Controller
    {
        // GET: Inspector
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ShowInspectorName()
        {
            string inspectorName = "avi";
            ViewBag.InspectorName = inspectorName;
            return View();
        }
        public ActionResult ShowInspector()
        {
            return View();
        }
        public ActionResult GetAllInspectorsNames()
        {
            string[] inspectorsNames = new string[] { "wsds", "ronu", "youda", "masn", "yas", "wewe" };
            ViewBag.InspectorsNames = inspectorsNames;
            return View();
        }

        public ActionResult GetAllInspectors()
        {
            return View();
        }
         
        public ActionResult InspectorOjb()
        {
            Inspector inspector = new Inspector("matan", "ysayas", 1996, 6);
            return View(inspector);
        }

        public ActionResult InspectorList() {
            
                List <Inspector> inspectorsList=new List<Inspector>();
            inspectorsList.Add(new Inspector("bob", "sdsd", 1585, 5));
            inspectorsList.Add(new Inspector("dfb", "sdsd", 1785, 7));
            inspectorsList.Add(new Inspector("bobi", "eeeed", 1655, 9));
            inspectorsList.Add(new Inspector("avner", "sdsd", 1985,7));
            return View(inspectorsList); 
        }

    }
}

FactoryWebApplication/Controllers/ManagerController.cs
using FactoryWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FactoryWebApplication.Controllers
{
    public class ManagerController : Controller
    {
        // GET: Manager
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ShowManagerName()
        {
            string managerName = "rob";
            ViewBag.ManagerName = managerName;
            return View();
        }
        public ActionResult ShowManager()
        {
            return View();
        }
        public ActionResult GetAllManagersNames()
        {
            string[] managersNames = new string[] { "avi", "ronu", "yoni", "matan", "yosi", "avner" };
            ViewBag.ManagersNames = managersNames;
            return View();
        }

        public ActionResult GetAllManagers()
        {
            return View();
        }

        public ActionResult ManagerOjb() {
            Manager manager = new Manager("rob","you","web");
            return View(manager); 
          }



        public ActionResult ManagerList() { 
        
            List<Manager> list = new List<Manager>();
            list.Add(new Manager("vova", "asas", "asas"));
            list.Add(new Manager("eee", "erdfs", "dfdfas"));
            list.Add(new Manager("touda", "sdsds", "sdsdsdsd"));

            return View(list);
        
        }
    }
}

FactoryWebApplication/Views/Employee/EmployeeList.cshtml
@{
    ViewBag.Title = "EmployeeList";
}

<h2>EmployeeList</h2>

@foreach (var item in Model)
{
<div>
    <h1>@item.firstName</h1>
    <h1>@item.lastName</h1>
    <h1>@item.yearOfBirth</h1>
    <h1>@item.phone</h1>
</div>

}

FactoryWebApplication/Views/Employee/EmployeeOjb.cshtml
@{
    ViewBag.Title = "EmployeeOjb";
}

<h2>EmployeeOjb</h2>

<h2>@Model.firstName</h2>
<h2>@Model.lastName</h2>
<h2>@Model.yearOfBirth</h2>
<h2>@Model.phone</h2>

FactoryWebApplication/Views/Employee/ShowEmployee.cshtml
@{
    ViewBag.Title = "ShowEmployee";
}

<h2>ShowEmployee</h2>

FactoryWebApplication/Views/Employee/ShowEmployeeName.cshtml
@{
    ViewBag.Title = "ShowEmployeeName";
}

<h2>ShowEmployeeName</h2>
<h1>@ViewBag.EmployeeName</h1>

FactoryWebApplication/Views/Employee/ShowEmployees.cshtml
@{
    ViewBag.Title = "ShowEmployees";
}

<h2>ShowEmployees</h2>

FactoryWebApplication/Views/Employee/ShowEmployeesNames.cshtml
@{
    ViewBag.Title = "ShowEmployeesNames";
}

<h2>ShowEmployeesNames</h2>

@foreach(string item in ViewBag.EmployeeNames)
            {
                <h1>@item</h1>
            }

FactoryWebApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FactoryWebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FactoryWebApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FactoryWebApplication/Views/Inspector/GetAllInspectors.cshtml
@{
    ViewBag.Title = "GetAllInspectors";
}

<h2>GetAllInspectors</h2>

FactoryWebApplication/Views/Inspector/GetAllInspectorsNames.cshtml
@{
    ViewBag.Title = "GetAllInspectorsNames";
}

<h2>GetAllInspectorsNames</h2>

@foreach(string item in ViewBag.InspectorsNames)
            {
                <h1>@item</h1>
            }

FactoryWebApplication/Views/Inspector/InspectorList.cshtml
@{
    ViewBag.Title = "InspectorList";
}

<h2>InspectorList</h2>

@foreach (var item in Model)
{
    <div>
        <h1>@item.firstName</h1>
        <h1>@item.lastName</h1>
        <h1>@item.yearOfBirth</h1>
        <h1>@item.workExperience</h1>
    </div>

}

FactoryWebApplication/Views/Inspector/InspectorOjb.cshtml
@{
    ViewBag.Title = "InspectorOjb";
}

<h2>InspectorOjb</h2>
<div>
    <h1>@Model.firstName</h1>
    <h1>@Model.lastName</h1>
    <h1>@Model.yearOfBirth</h1>
    <h1>@Model.workExperience</h1>
</div>  

FactoryWebApplication/Views/Inspector/ShowInspector.cshtml
@{
    ViewBag.Title = "ShowInspector";
}

<h2>ShowInspector</h2>

FactoryWebApplication/Views/Inspector/ShowInspectorName.cshtml
@{
    ViewBag.Title = "ShowInspectorName";
}

<h2>ShowInspectorName</h2>

<h1>@ViewBag.InspectorName</h1>

FactoryWebApplication/Views/Manager/GetAllManagers.cshtml
@{
    ViewBag.Title = "GetAllManagers";
}

<h2>GetAllManagers</h2>

FactoryWebApplication/Views/Manager/GetAllManagersNames.cshtml
@{
    ViewBag.Title = "GetAllManagersNames";
}

<h2>GetAllManagersNames</h2>

@foreach(string item in ViewBag.ManagersNames)
            {
                <h2>@item</h2>
            }

FactoryWebApplication/Views/Manager/ManagerList.cshtml
@{
    ViewBag.Title = "ManagerList";
}

<h2>ManagerList</h2>

@foreach(var item in Model)
            {
                <div>
                    <h1>@item.firstName</h1>
                    <h1>@item.lastName</h1>
                    <h1>@item.department</h1>
                   
                </div>
            }

FactoryWebApplication/Views/Manager/ManagerOjb.cshtml
@{
    ViewBag.Title = "ManagerOjb";
}

<h2>ManagerOjb</h2>

<h1>@Model.firstName</h1>
<h1>@Model.lastName</h1>
<h1>@Model.department</h1>

FactoryWebApplication/Views/Manager/ShowManager.cshtml
@{
    ViewBag.Title = "ShowManager";
}

<h2>ShowManager</h2>

FactoryWebApplication/Views/Manager/ShowManagerName.cshtml
@{
    ViewBag.Title = "ShowManagerName";
}

<h2>ShowManagerName</h2>

<h2>@ViewBag.ManagerName</h2>

FactoryWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("employee name", "ShowEmployeeName", "Employee")</li>
                    <li>@Html.ActionLink("all employes names", "ShowEmployeesNames", "Employee") </li>
                    <li>@Html.ActionLink("inspector name", "ShowInspectorName", "Inspector")</li>
                    <li>@Html.ActionLink("all inspectors", "GetAllInspectorsNames","Inspector")</li>
                    <li>@Html.ActionLink("manager name", "ShowManagerName", "Manager")</li>
                    <li>@Html.ActionLink("all managers names", "GetAllManagersNames", "Manager")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>